### ISSUE TITLE
Rewrite Installation for Windows

### ISSUE THREAD

**Issue by flywire** [saufrecht/ledger-explorer#3]
[Make a virtual environment](https://github.com/saufrecht/ledger-explorer#make-a-virtual-environment) and [Publish your data](https://github.com/saufrecht/ledger-explorer#publish-your-data) needs to be rewritten for windows.

[Publish your data](https://github.com/saufrecht/ledger-explorer#publish-your-data)

>Ledger Explorer loads data from a URL. So, if you want to load your Gnucash export, which is a local file, you have to publish that file on a webserver that your browser can access.

How is this done in Windows? (Trying to run `sample_data.csv`.)

Maybe: [How to Install and Run the Nginx Server on Windows 10](https://www.maketecheasier.com/install-nginx-server-windows/).

**Comment by flywire** [comment]
Commit 83e0068 is an improvement but the virtual environment is still confusing. Hopefully, another user will jump in.

Progressing with `nginx`
```
E:\nginx-1.19.2>python /ledger-explorer/ledger_explorer/index.py
Traceback (most recent call last):
  File "/ledger-explorer/ledger_explorer/index.py", line 9, in <module>
    from apps import balance_sheet, cash_flow, data_source
  File "E:\ledger-explorer\ledger_explorer\apps\cash_flow.py", line 320
    if (len_sub := len(sub_accounts)) > 0:
                ^
SyntaxError: invalid syntax
```

**Comment by saufrecht** [comment]
Ledger Explorer requires Python 3.8.  I'll update the README.

**Comment by saufrecht** [comment]
I set up a live version so that people can skip installation.  [Have a look, with sample data pre-loaded](https://ledge.uprightconsulting.com/ex/?transu=https://ledge.uprightconsulting.com/s/sample_transaction_data.csv&atreeu=https://ledge.uprightconsulting.com/s/sample_transaction_account_tree.csv&etreeu=https://ledge.uprightconsulting.com/s/sample_transaction_eras.csv&init_time_res=5).
